n1 = input('Digite um número: ').strip()
n2 = input('Digite outro número: ').strip()

soma = float(n1) + float(n2) 
soma_s = str(float(n1)) + str(int(n2) )
mult = float(n1) * float(n2)
mult_s = str(float(n1)) * int(n2)
divisão = float(n1) / float(n2)
divisão_int = float(float(n1) // float(n2))
expoente = float(n1) ** float(n2)
resto = float(n1) % float(n2)

print(f"A soma dos números é igual a {soma}")
print(f"A concatenação das strings é igual a {soma_s}")
print(f"A multiplicação dos números é igual a {mult}") 
print(f"A multiplicação como strings é igual a {mult_s}") 
print(f"A divisão dos números é igual a {divisão}") 
print(f"A divisão inteira dos números; é igual a{divisão_int}")
print(f"A exponenciação é igual a {expoente}")
print(f"O módulo (resto) é igual a {resto}")